menu:
  æ•£è½çš„å¶å­: /
  # å…³äºæˆ‘: /about
  # å‹é“¾: /friends

favicon: /img/favicon.ico
logo: /img/favicon.ico
cover: /img/cover.png

contact:
  Email: [mailto:aneureka2@gmail.com, "ğŸ’Œ"]
  Github: [https://github.com/aneureka, "â­ï¸"]
  Twitter: [https://twitter.com/Aneureka, "ğŸ¦"]

startyear: 2017
